[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configuración para Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Variables de entorno que se configurarán en Netlify
[context.production.environment]
  DATABASE_URL = ""

# Configuración de redirecciones para Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para archivos estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
